server:
  port: 8082

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:mysql://localhost:3306/catalog_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6379
  # Thêm khối kafka này vào cùng cấp độ thụt lề với datasource, jpa, data
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: catalog-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: java.util.HashMap
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Cấu hình JWT
jwt:
  # Chữ ký bí mật (Đã mã hóa Base64). Chuỗi này ít nhất phải 256-bit (tương đương 32 ký tự).
  secret: 4b6a4a6e744e6b726466384a51356f5a774652417757367838536b5952674261
  # Thời hạn Access Token tính bằng mili-giây (15 phút = 900000)
  expiration: 900000
  refresh-expiration: 604800000

